export default {
  FORM_SUBMIT_URL: '',
  SET_FORM_DATA: 'SET_FORM_DATA',
  SET_ACTIVE_ELEMENT: 'SET_ACTIVE_ELEMENT',
  SET_VALUE: 'SET_VALUE',
  ADD_SUGGEST: 'ADD_SUGGEST',
  ADD_PARAMS: 'ADD_PARAMS'
};
